version: "3.9" # the version of the docker-compose synatx that we are going to use

# The docker-compose.yml conatin one or more services that are needed for our application.
services:
  app: # Name of a first service
    build: # service should be build from the dockerfile located in the current directory.
      context: . # current directory
      args:
        - DEV=true
    ports: # through this port we can access this service on our local machine
      - "8000:8000"
    volumes: # It is the way of mapping our directory to our docker container
      - ./app:/app
    command: > # command that is used to run the server.
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment: # sets the env variables that the application inside the container can use.
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db: # this is the name of the second service
    image: postgres:13-alpine # it specifies the service should use the postgres:13-alpine docker image
    volumes:
      - dev-db-data:/var/lib/postgresql/data # creates a named volume dev-db-data and mounts it to the directory on the container. This volume is used to persist the postgreSQL data.
    environment: # sets env variables for the postgreSQL container
      - POSTGRES_DB=devdb # database name
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes: # defination of named volume
  dev-db-data:
