---
name: Checks

on: [push]

jobs:
  test-lint: # job id
    name: Test and Lint
    runs-on: ubuntu-20.04 # our jobs runs on
    steps:
      - name: Login to Docker Hub # The name that is visible on github action interface
        uses: docker/login-action@v1 # used for login
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"